### ISSUE TITLE
Recycling of Cars and Tanks

### ISSUE THREAD

**Issue by Flagran** [harag-on-steam/se-recycling-extras#4]
Hey Harag,

Thanks 4 your mod it keeps my storage cheasts clean because i play with die RuinsMod thereis always a small powerpole whaiting 4 recycling.

So i taped in something funny. Because i use the Ruinsmod i found nearly 50 cars around nauvis and my other outposts. I dont need them but i dont like to destroy the cars. 

I also have several tanks mk1 and mk2 from k2 that i dont need since i get the spidertron.

Do you see a chance to add the recycling of cars / tanks and k2 tanks?

Greetings 

Flagran

**Comment by harag-on-steam** [comment]
I don't think that would be recipes that get used often. So I don't think it's worth it.
